### ISSUE TITLE
F-Droid integration

### ISSUE THREAD

**Issue by GETandSELECT** [ivpn/android-app#1]
Can you please submit this app to F-Droid?

thanks

**Comment by AlexKorvin** [comment]
> Can you please submit this app to F-Droid?
> 
> thanks

Hey, we are working on it, it's our next priority, unfortunately, it can't be done right now, first need to apply some changes on the code.

**Comment by GETandSELECT** [comment]
Thank you.

What exact work required for the app to be published on F-Droid?

**Comment by AlexKorvin** [comment]
Hello, besides our own code, we need to automate building OpenVPN and WireGuard binaries from source codes in the f-droid environment.

**Comment by Bubu** [comment]
We discovered, that the [com.android.billing](https://github.com/ivpn/android-app/blob/master/app/build.gradle#L180) module, while itself being free software pulls in nonfree google libraries. The F-Droid version cannot ship with this.

F-Droid issue here: https://gitlab.com/fdroid/fdroiddata/-/issues/2070
