### ISSUE TITLE
Random server for Exit hop does not work with WireGuard Multi-hop

### ISSUE THREAD

**Issue by edwardivpn** [ivpn/android-app#104]
# Bug report

## Describe your environment

* Device: Huawei P20
* OS name and version: Android 10
* IVPN app version: 2.8.0
  
## Describe the problem

When choosing a Random server for Exit hop WireGuard Multi-hop, the app always selects the same server that has been previously set manually.

### Steps to reproduce:

1. Set VPN protocol to WireGuard and enable Multi-hop
2. Set Exit server to Random
  
### Observed Results:

The app constantly connects to the same Exit server.
  
### Expected Results:

The app should connect to a Random Exit server.
  
### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by gorkapernas** [comment]
Verified fixed on version 2.9.0, Samsung Galaxy S10 Android 11 and Pixel 4 Android 12, the exit server always select a different random server every time the user reconnects or when tapping on "random server" on the list of servers while connected.
