### ISSUE TITLE
The exit hop server is not displayed in the notifications area (wireguard/multi-hop)

### ISSUE THREAD

**Issue by edwardivpn** [ivpn/android-app#105]
# Bug report

## Describe your environment

* Device: Huawei P20
* OS name and version: Android 10 
* IVPN app version: 2.8.0 
  
## Describe the problem

The Exit hop server is not displayed in the notifications area when using a WireGuard Multi-hop connection.

### Steps to reproduce:

1. Set VPN protocol to WireGuard and enable Multi-hop
2. Connect

### Observed Results:

Notifications area only display the Entry hop server:

![wgmulti](https://user-images.githubusercontent.com/38722691/140693712-660ca4e5-34cb-4d7a-baac-2b1e208d633d.jpg)
  
### Expected Results:

Notifications area should display both Entry and Exit hop servers:

![openvpn_multi](https://user-images.githubusercontent.com/38722691/140693777-b40404fb-1c95-4da4-bd41-8a6bf13888f3.jpg)
  
### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by gorkapernas** [comment]
Verified fixed on version 2.9.0, Samsung Galaxy S10 Android 11 and Pixel 4 Android 12, the notification display both entry and exit servers when connected with MultiHop for WireGuard.
![notification_fixed](https://user-images.githubusercontent.com/16647612/142841158-36d9ec98-359b-41d2-84ad-02e3674dfbf2.png)
