### ISSUE TITLE
WireGuard Multi-hop warning message displayed when changing port with OpenVPN selected

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#112]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Android 8  
* IVPN app version: 2.8.1  
  
## Describe the problem

Choosing WireGuard Multi-hop prevents switching the port for OpenVPN connections.

### Steps to reproduce:

1. Choose Multi-Hop with WireGuard and connect the VPN.
2. Disconnect the VPN.
3. Switch Protocol to OpenVPN (Multi-Hop still enabled).
4. Tap the `Preferred port & protocol` menu.
  
### Observed Results:

A warning about Multi-Hop and WireGuard is presented and the port cannot be changed.
  
### Expected Results:

Allow the port to be changed.

**Comment by gorkapernas** [comment]
Verified on v2.8.3, Redmi 5 Android 8, Pixel 4 Android 12, the issue no longer occurs. 
Currently when selecting OpenVPN - MultiHop, only "UDP/TCP" can be selected, not the port number. This is part of the implementation for the port based MultiHop for OpenVPN. 
Please refer to https://github.com/ivpn/android-app/issues/119 for further details.
