### ISSUE TITLE
RFE: use custom hosts file as a blocklist

### ISSUE THREAD

**Issue by lsm5** [ivpn/android-app#113]
# Feature request

## Description

In addition to the ability to use a custom DNS, it would be nice if the app allowed me to load a custom hosts file for blocking additional hosts not blocked by DNS/antitracker. Would be especially desirable for unrooted devices where I can't use a separate DNS / firewall app if I'm already using IVPN.

## Describe the solution you'd like

Ideally a field in settings which takes a path to a text file that is either compatible with /etc/hosts or with dnscrypt-proxy.

## Describe alternatives you've considered

Nothing compatible with IVPN on unrooted devices AFAIK.

**Comment by d4f5409d** [comment]
Like I mentioned here, users are searching for these features, which in my personal honest opinion would be awesome to have. Firewall, and you could select which apps to not have internet, similar to Netguard app. https://github.com/ProtonVPN/android-app/issues/94#issuecomment-1422819290

**Comment by trymeouteh** [comment]
I would like to be able to edit the hosts file with IVPN. There is this app which is available on F-Droid that allows this but has not been maintained in a few years and it does the job, but to use this app, I need to disable IVPN and disable the VPN settings for IVPN.

https://github.com/x-falcon/Virtual-Hosts

Would be great if editing the host was a built in feature on IVPN for android and iOS.

**Comment by jurajhilje** [comment]
This feature is not planned at the moment.
