### ISSUE TITLE
Servers change randomly when switching protocols

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#120]
### Description:
On IVPN version 2.8.1, when switching protocols, the servers change randomly.
The issue happens with both SingleHop and MultiHop.

**Note:**
The issue is not observed on iOS and desktop apps.

### Expected result:
The servers should be remembered when switching protocols.

### Steps to reproduce:
1. Install version 2.8.1.
2. Login.
3. Connect / Disconnect to / from any random server.
4. Switch protocols from WireGuard to OpenVPN and vice versa, multiple times.
5. Observe that the servers change randomly.

### Video:
https://user-images.githubusercontent.com/16647612/158831346-c83921ee-2524-4e85-ae56-822f24fc5f99.mp4

### Environment:
IVPN: 2.8.1
Device: Pixel 4 Android 12

**Comment by gorkapernas** [comment]
@jurajhilje I still experience the issue, but it seems it's something different from what I initially reported.

The issue happens when "fastest server" is selected, apparently the app resets the servers latency when switching protocols OR when changing from SingleHop to MultiHop (and vice versa), that's why every time I change the protocol or switch between SingleHop and MultiHop, I can see different servers.
I don't see this behavior on iOS, the servers latency is never reset when switching protocols or between SingleHop and MultiHop.

**Comment by jurajhilje** [comment]
@gorkapernas
iOS app does reload latency information when switching protocols, but does not when enabling/disabling MultiHop. The Android app should have the same logic.
I cannot reproduce reseting latency (app changing the fastest server) when enabling/disabling MultiHop.

**Comment by jurajhilje** [comment]
@gorkapernas I was able to reproduce the issue on my end:

1. Keep refreshing servers latency (pull to refresh on the servers list)
2. Observed that on some occasions, the latency information is missing for all servers

The issue is related to the ping service, so I suggest we open a new issue for this.

**Comment by gorkapernas** [comment]
FYI, @jurajhilje new issue created as requested -> https://github.com/ivpn/android-app/issues/220

I'll move this ticket to deployable since this ticket does not require more testing.
