### ISSUE TITLE
Bring DNS-over-HTTPS to Android

### ISSUE THREAD

**Issue by divdus-tarnus** [ivpn/android-app#123]
# Feature request

## Description

Consider porting DNS-over-HTTPS to Android for feature parity with iOS

## Describe the solution you'd like

Would like to be able to use DNS-over-HTTPS in the Android app, similarly to iOS.

## Describe alternatives you've considered

Have you considered any alternative solutions or workarounds?

N/A — Adguard VPN supports this on Android, but would prefer to stick with IVPN!

**Comment by Silverslyth** [comment]
i would like to use my NEXTDNS with IVPN , i hope this feature will get implemented sooner .

**Comment by jurajhilje** [comment]
DNS-over-TLS can be set using the Android OS native Private DNS feature.

Regarding DNS-over-HTTPS, some Android 13 devices have support (also using Private DNS feature), however it seems to be limited to selected providers.

**Comment by arekscode** [comment]
+1
The desktop app uses dnscrypt iirc, there are some apps on Android that also make use dnscrypt for DoH functionality. I'm assuming the iOS app uses dnscrypt as well, so I don't see why that wasn't included in the Android app.

**Comment by mjdNjhNJ** [comment]
I would like to see this implemented directly into the app as well. I don't think relying on system DNS could be considered an alternative if user want to filter DNS requests for VPN.
