### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Jpersh27** [ivpn/android-app#13]
@AlexKorvin @jurajhilje 

1.) Expand Anti Tracker by improving Its blocking capabilities by allowing users the ability: To add a custom blocking list option too improve upon Anti Trackers current blocking capabilities.
 
(Examples of popular and open source block list/filters include- Easy List, Easy Privacy, Ad Guards filters, Fanboys filters, etc...)

-"Edward De, From IVPN Support" informed me via email on 01/18/21 the following- "Yes, it's on our to-do list, though I have no firm ETA to share for when this feature becomes available."

Thank you and hope to hear back from someone soon!

**Comment by jurajhilje** [comment]
Hi @Jpersh27 !
Thanks for your question. I can confirm what Edward said.  
As soon as there is more concrete info about this, we will report here as well.

**Comment by Jpersh27** [comment]
Thank you for your response and sounds great I will wait for new updates. 

I do have another feature request for the Android version of IVPN if you don't mind? @AlexKorvin @jurajhilje 

1.) Is there any plans to utilize or introduce the Mock Location feature under Android Developer Settings?

With the GPS Override feature activated within the IVPN application, any app that requests access to a users physical coordinates will be overridden by the coordinates of a selected VPN server. 

-For example, say a user is physically located in the USA and is connected to one of IVPN's servers in Switzerland. Whenever an app on their Android Smartphone asks for their location, it will now receive the location of the VPN server in Switzerland as opposed to their actual GPS location in the USA. 

One current well known vpn service called ''Surf Shark" offers this feature already, and its already been added to there Android version of there application. I tested there service and utilized this feature and it was easy to enable it under developer options.

I used it on two diffrent Android phones and two diffrent versions of Android. Versions being Android 9 pie and Android 10 Q. The feature worked seamlessly and didn't leak my location ever, and matched the same location of the server I was connected too. Overall I think its a useful feature and better then having to use a third party app alongside your vpn to spoof your GPS Location.

Thank you and I hope I explained everything well enough and hope to hear back from someone soon.

**Comment by Jpersh27** [comment]
@jurajhilje @AlexKorvin @gorkapernas It has been 10 months since this issue has been opened and no one has given me an update to let me know if any plans have been made to support this feature...

1.) If at all possible would someone please provide me with an update on this feature?

**Comment by jurajhilje** [comment]
Hi @Jpersh27,
I cannot say if and when this is going to be prioritised.
I can suggest using your own pre-configured custom DNS with our apps. NextDNS for example works well with our apps.
