### ISSUE TITLE
Incorrect Multi-hop text on Protocol screen

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#130]
# Bug report

## Describe your environment

* Device: _____  
* OS name and version: Android 8  
* IVPN app version: 2.8.2  
  
## Describe the problem

Go to the IVPN App's `Settings > VPN Protocol` area and check the text under WireGuard.  There is a sentence about how Multi-hop is only supported for OpenVPN.

Please remove this one sentence.  Thanks.

**Comment by gorkapernas** [comment]
Verified fixed on 2.8.3, Redmi Note 10 Android 11, Pixel 4 Android 12, the text has been updated accordingly.
See screenshot below.
![text_fixed](https://user-images.githubusercontent.com/16647612/170975403-d0b44c24-c7d2-462d-bbc4-82bf116c426e.png)
