### ISSUE TITLE
Fetch ports from servers.json

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#139]
Fetch ports from `/v5/servers.json` API.

**Comment by gorkapernas** [comment]
@jurajhilje not sure if it's related to this, but it seems like after fetching ports from `v5/servers.json`, the default port for OpenVPN is TCP 443. The expected should UDP 2049.

**Comment by gorkapernas** [comment]
Verified fixed the last issue reported, the default port for OpenVPN is 2049 as expected.
