### ISSUE TITLE
Network protection - Cannot add wifi network as trusted 

### ISSUE THREAD

**Issue by cox34** [ivpn/android-app#150]
# Bug report

## Describe your environment

* Device: Samsung S10e  
* OS name and version: stock Android 12  
* IVPN app version: 2.6.0  
  
## Describe the problem
No "scanned networks" appear in the "network protection" settings. 

I have tried enabling/disabling killswitches, the vpn itself, mobile data, wifi networks and other possibly related settings and have been unable to add a desired wifi network to the "saved" tab, as there are no "scanned" networks to select. 

What is the intended way to make networks appear in the "scanned" section?

It only says "Once we find a WiFi networks they will be displayed here" (non-issue but you could also change "networks" to "network")

**Comment by jurajhilje** [comment]
@cox34 I haven't tested this on my end, but I got some info from our QA engineer.

1. First of all, when enabling Network Protection, the user should be presented with this message:

<img src="https://user-images.githubusercontent.com/3176222/183443378-565ad688-12ce-4d70-ad2b-d5f6722ccc82.png" width="350">

2. Then, the user needs to tap on Settings to open the Android Settings for the IVPN app.

3. From here, the user needs to do the following: Tap "Permissions" -> Tap "Location" -> Select "Allow all the time"

And that should be it. I hope this helps to resolve your issue. I suspect that in your case, it is related to allowing the permission.

**Comment by cox34** [comment]
IVPN location's permission was already set to "allow all the time", and was set as such when I did some troubleshooting. 
But it turns out location wasn't enabled (I usually only enable it when needed). After enabling location, I was able to add a trusted network. Thank you.

**Comment by jurajhilje** [comment]
OK, I'm glad to hear that you resolved the issue.
