### ISSUE TITLE
Inconsistent AntiTracker availablity on in-app payment screen

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#154]
# Bug report

## Describe the problem

On website, AntiTracker is available for both IVPN Standard and IVPN Pro:
https://www.ivpn.net/pricing/

On in-app payment screen in Google Play store release, AntiTracker is only listed as available for IVPN Pro

![android-payment-antitracker3](https://user-images.githubusercontent.com/74565577/183776719-576c6817-b748-45fb-a7ad-3f39514f1d5e.png)

Either:
1. Remove AntiTracker from payment screen in Google Play store release entirely, or
2. Include AntiTracker in both Standard and Pro sections with a popup explaining that AntiTracker is not available in Google Play store release

Thanks.

**Comment by gorkapernas** [comment]
Verified fixed on 2.8.4, AntiTracker is now displayed on both plans, without tooltip though, as Juraj pointed out, the user is buying a service and the account can be used on different platforms and Android versions, so listing all the available features in this case makes sense.
