### ISSUE TITLE
Screen shows bright white background on launch with dark mode

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [ivpn/android-app#157]
# Bug report

## Describe your environment

* Device: Google Pixel 3
* OS name and version: Android 12
* IVPN app version: 2.8.3
  
## Describe the problem

The screen flashes bright white on app launch, which disrespects the dark theme, and hurts my eyes.

### Steps to reproduce:

1. Open the app when it is not running. This may not occur on the latest smartphones due to them skipping this screen with their fast CPUs.
  
### Observed Results:

The screen shows bright white for a split second with the IVPN app icon on top. 
  
### Expected Results:

The screen should respect the dark theme and show the same screen but with a black background

**Comment by gorkapernas** [comment]
@jurajhilje I'm not sure that the issue is fixed, I still see a white screen just before the IVPN app is launched, this is the same behavior I can see in older builds.

**Comment by jurajhilje** [comment]
@gorkapernas 
After testing IVPN and other Android apps, I can see that majority of them don't have a theme override in the app settings but just automatically adapt theme to system settings. What we have is useful for older Android verions that have no night mode option, but it's not really needed for newer versions. For the new Android verison I think we should remove it from app's settings and just use theme from system settings.

I didn't find appropriate way to fix the issue with the splash screen when using theme override. There is a hack probably but I would not consider that as a proper solution.

Can you confirm that the issue with light splash screen (System Settings: dark theme, IVPN app Settings: System default) is fixed?

**Comment by gorkapernas** [comment]
@jurajhilje yes, I confirm that the launch screen displays in dark mode when system settings: "dark theme" + IVPN settings: "system default".
