### ISSUE TITLE
SignUpViewModel.openSite AndroidRuntimeException

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#172]
```
net.ivpn.client.signup.SignUpViewModel.openSite
android.util.AndroidRuntimeException
```

**Comment by gorkapernas** [comment]
Verified on 2.8.4, Redmi 5 Android 8, Redmi Note 10 Android 11, Pixel 4 Android 13, no crashes have been experienced when redirecting legacy accounts to the website signup or when signing up with new accounts.
