### ISSUE TITLE
InitialPaymentRequestBody NullPointerException

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#176]
```
net.ivpn.core.rest.data.addfunds.InitialPaymentRequestBody.<init>
java.lang.NullPointerException
```

**Comment by gorkapernas** [comment]
Verified on 2.8.4, Redmi 5 Android 8, Redmi Note 10 Android 11, Pixel 4 Android 13, no crashes have been found when initiating a payment with Google Play Store or similar scenarios.
