### ISSUE TITLE
Do not switch to OpenVPN when WG key rotation fails

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#18]
Currently, when the app fails to generate manually a new WireGuard key (e.g. internet connection error), the app shows an error, but immediately switches the protocol to OpenVPN. 

Since we now use WireGuard as the default protocol and for consistency with the other clients, we should do the following.

When manual key rotation fails:
- Show an error (see screenshot below taken from iOS for reference)

![iOS_WG key error](https://user-images.githubusercontent.com/16647612/109502088-d3163e00-7a98-11eb-8db7-0b33dea0e48a.png)

- Once the error is dismissed, the app keeps WireGuard as protocol + old active key

**Steps to reproduce:**
1. Enable Airplane mode
2. Attempt to generate manually a new key

**Comment by AlexKorvin** [comment]
@gorkapernas
Hey Gorka. 
We shouldn't keep the old WireGuard key on regenerating error. 
There could be a case when the server removed the old key, but the Android client doesn't receive a response. And then there will be no connection when connecting to our gateways.

**Comment by gorkapernas** [comment]
@AlexKorvin The issue happens when trying to regenerate **manually** a new WG key without e.g. internet connection, but the existing key is still active. In such cases, I think it is not needed to change the protocol, the user can retry to manually generate the key after the connection is reestablished.
FYI, the issue  is not observed on iOS or desktop apps.

**Comment by gorkapernas** [comment]
Verified on version 2.4.0, Samsung G S10/Android 11, Huawei MediPad T5/Android 8, when manual key rotation fails (e.g. no internet connection), the app presents an error, but it does not change the protocol to OpenVPN. The old key is removed from the system, so there will be empty fields in the WireGuard Details screen, however, once the connection is reestablished, a new key will be generated upon connection to the VPN or when doing it manually. 
This looks good to go.
