### ISSUE TITLE
Firewall activated via Network Protection does not block traffic in certain cases

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#19]
### Description:
The Firewall stops blocking the traffic after manually disconnecting from the VPN server, then connecting and disconnecting from the VPN server again while being on 'Untrusted network' and having the 'Enable kill-switch' option checked in Network Protection Rules area.

Although 'Kill-switch active' notification is displayed, the Internet access is not blocked.

The issue does not seem to occur when the 'main' Killswitch is toggled  'On'. 

### Steps to reproduce:
1. Activate Network Protection and have 'Enable kill-switch' option checked for 'Untrusted networks.
2. Connect device to an 'Untrusted network' - the app connects to the VPN and enables the Firewall as expected.
3. Manually disconnect from the VPN - the Firewall is blocking the traffic as expected.
4. Reconnect to the VPN server, then disconnect back - the app's notification shows the Firewall is enabled but traffic is not blocked.

### Environment:
Device, OS: Samsung G S10/Android 11, Huawei MediPad T5/Android 8
IVPN version: 2.3.0

**Comment by Heryt944** [comment]
Why this issue has medium priority? I considers it a security risk.

**Comment by gorkapernas** [comment]
Verified on version 2.4.0, Samsung G S10/Android 11, Huawei MediPad T5/Android 8, the issue described in the ticket no longer occurs. Enabling KillSwitch upon connecting to an untrusted network works as expected, every time the user disconnects from the VPN with an untrusted network, the internet traffic is blocked.

Please note that once the KillSwitch is enabled for the untrusted network, it is also enabled in the main application settings, so it will always be enabled until the user disables KillSwitch manually. Same occurs when disabling KillSwitch for trusted networks, it will also disable the KillSwitch forever on connection to a trusted network.
