### ISSUE TITLE
Server/Country Blacklist

### ISSUE THREAD

**Issue by piped84** [ivpn/android-app#206]
Hi
Would you please consider adding a server and country blacklist?

What i specifically mean by this is a list that a specific server or a hole country can be put into.
When a server or country is put into this list the server or servers pertaining to a specific country will no longer be available in the server list nor will it be possible to connect to it using the "fastest server" feature.

**Comment by jurajhilje** [comment]
IVPN app has two features that helps to accomplish mentioned above:
- Blacklist for excluding servers/locations from the fastest server selection
- Possibility to build list of favorite servers
