### ISSUE TITLE
Update AGP

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#208]
Update AGP to newer versions.

- Update AGP to 7.1.3
- Add [ics-openvpn](https://github.com/schwabe/ics-openvpn) to ACKNOWLEDGEMENTS.md

This issue is related to #205

**Comment by gorkapernas** [comment]
Tested on version 2.8.5, Samsung Galaxy S11 Android 12, Pixel 4 Android 13, the issue with OpenVPN has been solved.
No more outstanding issues found related to this version.
