### ISSUE TITLE
Internet blocked when using OpenVPN + MultiHop + AnTitracker

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#212]
### Description:
When connecting with OpenVPN + MultiHop + AntiTracker, the internet connection will be blocked. The issue does not seem to happen with SingleHop or Custom DNS.

### Expected result:
Internet connection should not be blocked.

### Steps to reproduce:
1. Install site version 2.8.4.
2. Login.
3. Select OpenVPN as protocol.
4. Enable AntiTracker.
5. Enable MultiHop.
6. Connect and observe the issue.

### Environment:
IVPN: 2.8.4
Devices: Samsung Galaxy S11 Android 12, Pixel 4 Android 13

**Comment by edwardivpn** [comment]
This occurs because the client sets incorrect DNS:
```
14:30:47.506 OpenVPNThread : PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,explicit-exit-notify 3,comp-lzo no,route-gateway 10.56.44.1,topology subnet,ping 10,ping-restart 60,dhcp-option **DNS 10.56.44.1**,ifconfig 10.56.44.5 255.255.252.0,peer-id 3,cipher AES-256-GCM'
```
The correct DNS address for Multi-hop connections should be the following:

10.0.254.101 = regular DNS with no blocking
10.0.254.2 = standard AntiTracker to block advertising and malware domains 
10.0.254.3 = Hardcore Mode AntiTracker to also block Google and Facebook domains

**Comment by jurajhilje** [comment]
@gorkapernas Let me know if the last issue is resolved in the new APKs.

**Comment by gorkapernas** [comment]
Verified fixed in the latest apks, the initial issue described in the ticket, as well as the last issue reported in my last comment have been fixed.
I can confirm that the correct Antitracker DNS configuration is used with MultiHop and OpenVPN.
This is good to go.
