### ISSUE TITLE
[Feature Request] Include the app's version number (F-Droid, Google Play)

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#227]
# Feature request

## Description

A customer requests:

> The Android app does not display its own version number. It would be helpful if it did.

The version number is present in the website APK release in the update check area, but not in the F-Droid release and possibly not in the Google Play release (untested).

## Describe the solution you'd like

Add the version number to the bottom of the app's Settings area

## Describe alternatives you've considered

The version number is present on all release channels via the Android Settings > Apps > App Info area, but not in the app itself.

--

Thanks.

**Comment by gorkapernas** [comment]
Verified on 2.9.0, the version number has been added to the bottom on the Settings screen.

![version numnber_android](https://github.com/ivpn/android-app/assets/16647612/d4f692d0-e48f-4907-82cc-1139118e75d0)

**Comment by gorkapernas** [comment]
Verified in the latest beta, only the version number is displayed at the bottom of the Setting's screen. This is good to go.

**Comment by gorkapernas** [comment]
@jurajhilje The version number is missing in the Google Play store build 2.9.0. See screenshot below.
<img width="338" alt="version missing" src="https://github.com/ivpn/android-app/assets/16647612/074dd571-ec5d-4639-9701-14bda3d2170e">

It looks like a regression bug ^^
