### ISSUE TITLE
Phone cannot cast when Bypassing VPN on Local Networks

### ISSUE THREAD

**Issue by CostcoFanboy** [ivpn/android-app#238]
# Bug report

## Describe your environment

* Device: Pixel 6 pro
* OS name and version: Android 13
* IVPN app version: 2.8.6
  
### Steps to reproduce:

1. Turn on Bypass VPN for Local Networks
2. Go on the YouTube app and go to a video
3. Press cast button and select a device
  
### Observed Results:

* Loading circle goes on to infinity and content is never chromecasted. 
  
### Expected Results:

* I expected my content to start playing on the device.

**Comment by edwardivpn** [comment]
If you have the native Android kill-switch enabled 'Bypass VPN for Local Networks' won't work. 

Check your phone's `Settings` > `Network & Internet` > `Advanced/VPN` area.

**Comment by CostcoFanboy** [comment]
> If you have the native Android VPN kill-switch enabled 'Bypass VPN for Local Networks' won't work.

Oh. I wasn't aware but this makes sense now that I think about it.. Thank you so much. I'll be closing the ticket.
