### ISSUE TITLE
error while generating signed apk for fdroid

### ISSUE THREAD

**Issue by TheTanmay1** [ivpn/android-app#244]
# Bug report

## Describe your environment

* Device: __HP Laptop 
* OS name and version: __linux mint___  
* IVPN app version: ____fdroid 2.8.6_  
  
## Describe the problem
after generating signed apk using android studio when i try checking the signed apk using linux mint terminal and apk signer i am getting this error :-  
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF

kindly help.

**Comment by jurajhilje** [comment]
IVPN Android app is available for download on F-Droid here https://f-droid.org/en/packages/net.ivpn.client/

I don't understand the use case where you need to build and sign the app on your end to be able to use it on F-Droid.
