### ISSUE TITLE
[BUG] New Update Version shows old Version.

### ISSUE THREAD

**Issue by barbiehunter** [ivpn/android-app#259]
# Bug report

## Describe your environment

* Device: Phone
* OS name and version: Oneplus Nord Android 12
* IVPN app version:  2.10.0
  
## Describe the problem
The app shows that there is a new update, but the update is the old 2.9.0 version

### Steps to reproduce:

1. Open the App
2. Go to the Settings
3. Go to Updates
  
### Screenshots:

Notification:
![image](https://github.com/ivpn/android-app/assets/38357837/a51444d6-87c8-4001-8ab8-b1f174a2c226)

In App Updates:
![image](https://github.com/ivpn/android-app/assets/38357837/db4889ce-7f52-412b-a2b4-ceddcaf0b67e)

**Comment by jurajhilje** [comment]
@barbiehunter Thanks for the report. This is now resolved.
There was an issue with CDN cache invalidation.
