### ISSUE TITLE
Add Port Forwarding and AntiTracker to the list of features for the PRO plan

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#26]
### Description:
Currently Port Forwarding and AntiTracker features are missing from the list of features for the PRO plan in the pricing screen.
Therefore we need to add these two features.

See screenshot taken from iOS for reference:
![proplan_Android](https://user-images.githubusercontent.com/16647612/111159285-39bb5180-8599-11eb-82d2-418ba7a3ae12.png)

**Comment by gorkapernas** [comment]
Verified on version 2.4.0, Samsung G S10/Android 11, Huawei MediPad T5/Android 8, the issue has been fixed. Port Forwarding and AntiTracker features have been added to the list of features for the PRO plan.

**Comment by AlexKorvin** [comment]
Done
