### ISSUE TITLE
Refactor OpenVPN connections to only use IP address

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#266]
## Description

In the current app version, if API experiences a failure and app obtains empty server IP set, the app will connect to OpenVPN server using hostname as a fallback. We want to refactor OpenVPN connections to only use IP address.

**Comment by gorkapernas** [comment]
Verified on version 2.10.3, Android 12 and 13, tested OpenVPN thoroughly without experiencing any issues related to these changes. 
There was an issue with the option "Bypass VPN for local networks" which was resolved on https://github.com/ivpn/android-app/issues/267
