### ISSUE TITLE
OpenVPN connections issues in the Android app from Accrescent

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#268]
### Description:
Initially reported by a customer, see description below.

```
It appears that for whatever reason the app does not connect via OpenVPN.

[2.10.0 does not work and caused the report]
2.10.1 also does not connect via OpenVPN.

I can confirm Version 2.9.0 works okay.

OnePlus 7T Pro  Android 12

I'll mention that the OpenVPN client app with config files work just fine.

I've tried Frankfurt, London and another city I don't remember. Both UDP and TCP.

From accrescent. And yes [issue occurs] on all networks I tried so far (4).


18:05:49.971 VpnStatus : New OpenVPN InitState VPN_GENERATE_CONFIG
18:05:49.971 IVPNService : startOpenVPN: profile Brussels, BE
18:05:49.976 IVPNService : stopOldOpenVPNProcess
18:05:49.976 IVPNService : forceStopOpenVpnProcess
18:05:49.977 IVPNService : started Socket Thread
18:05:49.980 OpenVPNThread : Unhandled exception: %1$s

%2$s
18:05:49.981 OpenVPNThread : Unhandled exception: %1$s

%2$s
18:05:49.982 IVPNService : showNotification: status = LEVEL_NOTCONNECTED
18:05:49.988 VpnStatus : New OpenVPN InitState NOPROCESS
18:05:49.989 IVPNService : processDied
18:05:49.989 IVPNService : endVpnService: starting
18:05:49.990 IVPNService : Cancel timer
18:05:49.990 IVPNService : endVpnService: stopForeground
18:05:49.991 IVPNService : Stop service
```
-----------

@jurajhilje I was able to reproduce the issue on Android 12 and 13, it is not possible to establish connection with OpenVPN. WoreGuard works fine.
// Cc @jordan-ivpn 

### Environment:
IVPN: Accrescent 2.10.1
OS: Android 12 and 13

**Comment by jurajhilje** [comment]
I found that the default `bundletool build-apks` command cuts some resources required for OpenVPN. To fix the issue, we will build the APK set with `--mode=universal` to ensure that all app's resources are included.

**Comment by gorkapernas** [comment]
Verified fixed on Accrescent version 2.10.2. The issue described in the ticket no longer occurs.
OpenVPN works as expected, as well as WireGuard in the new version.

**Comment by gorkapernas** [comment]
Juraj:
"_I was not able to release the fixed Android app for Accrescent Store. I reached out to the Accrescent team on Matrix and got a response that --mode=universal (which we used to resolve the OpenVPN bug) is not supported. So I'll need to investigate into alternative way to fix the issue._"

**Comment by gorkapernas** [comment]
@jurajhilje OpenVPN works as expected, I also run a sanity and no issues were found.
It should be good to go.
