### ISSUE TITLE
Allow LAN access with VPN on

### ISSUE THREAD

**Issue by lsm5** [ivpn/android-app#27]
# Feature request
Allow LAN while being connected to VPN

## Description
This is so that I can connect for example youtube app to chromecast/google tv etc. while still being behind vpn. Currently, I either need to disable vpn or turn off vpn access for specific apps for lan access. (Hope I'm not missing something obvious :D )

## Describe the solution you'd like

This already seems to work in the linux cli app with `ivpn firewall -lan_allow`. So I guess something similar to that.

## Describe alternatives you've considered

Currently, I either need to turn off VPN or disable VPN access for some apps, which would be really nice to avoid :)

**Comment by AlexKorvin** [comment]
Thank you for feature request.

**Comment by gorkapernas** [comment]
Verified on version 2.4.0, Samsung G S10 / Android 11 and Huawei MediPad T5 / Android 8, after enabling the feature in the IVPN app settings, I was able to bypass the VPN connection when the device established connection to the local network , once the feature was disabled, LAN access was no longer available (if connected to the VPN). 
So currently, in this new Android version, it is possible to allow LAN traffic when connected to the VPN.

@lsm5 Please feel free to report back to us if you encounter any issues after we release the new Android version.

**Comment by lsm5** [comment]
@gorkapernas thanks!!! can't wait. Btw, do you release simultaneously to play store and f-droid? Asking because I install from f-droid.

**Comment by AlexKorvin** [comment]
@lsm5 Hey. We don't release simultaneously. Usually, the Google Play Store release happens one week earlier than on F-Droid. 

If something went wrong, we could update the version on Google Play Store much quicker than F-Droid one. But because of this, versions on F-Droid are always without critical issues and stable. 

If you want to be the first to receive updates and don't like Google Play Store, I can suggest using our website version.

**Comment by lsm5** [comment]
> If something went wrong, we could update the version on Google Play Store much quicker than F-Droid one. But because of this, versions on F-Droid are always without critical issues and stable.
> 
> If you want to be the first to receive updates and don't like Google Play Store, I can suggest using our website version.

@AlexKorvin i see, how about releasing rc / testing builds on f-droid or is it that f-droid releases need lot more work/time? I don't mind getting them from the website.

**Comment by AlexKorvin** [comment]
@lsm5 You are right. The update release time for F-Droid is bigger and more unpredictable. It could take 1 day or 1 week. And we can't affect it.

**Comment by lsm5** [comment]
works well with 2.4.0. Thanks a lot for this feature. Closing..
