### ISSUE TITLE
Notifications no longer show on Android 13

### ISSUE THREAD

**Issue by androidacy-user** [ivpn/android-app#278]
IVPN **must** declare the `POST_NOTIFICATIONS` permission on SDK33+ to be able to show notifications.

IVPN does not declare this permission, thus Android blocks all notifications with no possibility to unblock it.

**Comment by jurajhilje** [comment]
@androidacy-user Thank you for the report! Update/fix will be available ASAP.

**Comment by gorkapernas** [comment]
Verified fixed on version 2.10.4, IVPN notifications are showing again on Android 13+ devices.
