### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by fen0men102** [ivpn/android-app#282]
# Bug report

## Describe your environment

* Device: Samsung Galaxy S21, Exynos
* OS name and version: Android 13, One UI 5
* IVPN app version: 10.0.3
  
There are no notifications at all. It just looks like the app doesn't even have them - in device's settings, the "notifications" section for the app seems to be missing. Everything works fine on 10.0.0.

**Comment by edwardivpn** [comment]
https://github.com/ivpn/android-app/issues/278

**Comment by fen0men102** [comment]
Sorry, my fault!
