### ISSUE TITLE
Can't exclude non launchable apps

### ISSUE THREAD

**Issue by androidacy-user** [ivpn/android-app#285]
# Bug report

## Describe your environment

* Device: n/a
* OS name and version: android 13 
* IVPN app version: 2.10.4  
  
### Steps to reproduce:

1. Try to exclude Galaxy watch 6 manager 
2. Not in list
  
### Observed Results:

Not able to exclude non launchable apps 
  
### Expected Results:

Exclude any app with code
  
### Relevant Code:

If galaxy watch 6 manager is ran through a VPN, a lot of functionality breaks on the watch. Most apps can't get Internet access through Bluetooth if the app is through a VPN.

**Comment by jurajhilje** [comment]
@androidacy-user Thanks for the feedback. We will investigate and try to reproduce the issue. Can you confirm that you are referring to the Split Tunnel list with "Not in list"?

**Comment by gorkapernas** [comment]
Verified new changes on version 2.10.5.
@jurajhilje some of the non-launchable apps, as well as some of the system apps like Settings are displayed twice in the list of Split Tunnel. We should avoid displaying duplicates.

**Comment by gorkapernas** [comment]
Verified on the latest beta version, the issue reported on my previous comment has been fixed, the ST list doesn't display duplicates anymore.
Also I can confirm that non-launchable apps are now showing up in the list.
Tested on Android 8, 12 and 13.

**Comment by jurajhilje** [comment]
> Beta version?

@androidacy-user I'll ping you here as soon it's available.
