### ISSUE TITLE
Show gateways without IPv6 support

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#30]
## Description

This setting should be disabled (or hidden) and on by default.

When user enabled IPv6 for VPN tunnel, this setting should became visible. 

When both "Enable IPv4" and "Show gateways without IPv6 support" are enabled, on the servers list there should be "IPv6" label next to servers that support IPv6.

**Comment by gorkapernas** [comment]
Verified on version 2.5.0_production, during my last testing round I noticed that the option was hidden, but OFF by default, however, according to the requirements, the option should be hidden (or disabled) + ON.

Please change this accordingly.

**Comment by gorkapernas** [comment]
Verified on version 2.5.0, staging and production. 
Devices -Samsung Galaxy S10 Android 11 and Huawei MediaPad T5 Android 8.
The issue reported in my previous comment has been fixed, also there was an issue where the label `ipv6` was displayed even though the server did not support IPv6, this has also been resolved in the latest version.
Currently when enabling "show servers without IPv6", the label `ipv6` is shown next to the server that supports IPv6 in the list of servers. If the server doesn't support IPv6, the label is not shown. This only applies to WireGuard servers and when "IPv6 for WireGuard VPN"  is also enabled.
