### ISSUE TITLE
Traffic through IVPN app when using Hostspot mobile

### ISSUE THREAD

**Issue by ROG3RB0T** [ivpn/android-app#302]
# Feature request
Enable redirecting the traffic when sharing the internet using the hotspot mobile option.
## Description
When using the cellphone Mobile Hotspot option, redirect the traffic to use the IVPN connection.
A clear and concise description of the problem or missing capability.

Currently, when IVPN runs on the cellphone using mobile data, all the traffic is filtered throughout the IVPN, and the navigation is set with an IP from the IVPN server. But when using the sharing mobile data as a Hotspot mobile, the traffic isn't redirected to the VPN, and the devices connected to the shared network appear as if they are navigating using the ISP of the mobile network.
## Describe the solution you'd like
I want to share the internet's phone using the Mobile Hotspot option but redirecting the traffic to the IVPN network so the devices connected to the Hotspot will navigate using the IVPN and utilize the IP from the IVPN server, not the ISP mobile network from the cellphone. We can redirect all the traffic to the VPN for the Linux version, which could be possible in the Android App.

## Describe alternatives you've considered

Have you considered any alternative solutions or workarounds?
Only with the Windows Version can we share the internet connection using an external USB dongle, and the traffic is redirected to the VPN.

**Comment by edwardivpn** [comment]
Sharing a VPN connection via hotspot is impossible on Android devices without 'rooting' the system.
