### ISSUE TITLE
Android app version 2.10.5 crashed immediately upon opening

### ISSUE THREAD

**Issue by modestderp** [ivpn/android-app#306]
# Bug report

## Describe your environment

* Device: Samsung S10e
* OS name and version: Android 12  
* IVPN app version: 2.10.5 (from F-Droid)
  
## Describe the problem
After updating to 2.10.5 from 2.10.4 on F-Droid, opening the app will cause it to immediately crash. A black screen is very briefly shown before the app closes itself.

### Steps to reproduce:

1. Update IVPN Android app from 2.10.4 to 2.10.5.
2. Launch IVPN Android app.
  
### Observed Results:

* Opening the app will cause it to immediately crash. A black screen is very briefly shown before the app closes itself.
  
### Expected Results:

* The IVPN Android app version 2.10.5 launches normally after upgrade.

**Comment by jurajhilje** [comment]
@modestderp The fix is pending for release on F-Droid:
https://gitlab.com/fdroid/fdroiddata/-/issues/3154#note_1700378550

Original issue:
https://github.com/ivpn/android-app/issues/303

**Comment by Kartikeya-IYER** [comment]
@modestderp the new version v2.10.6 with the fix is now available in F-Droid and it works fine (at least for me, on multiple devices and Android versions). You should be able to directly upgrade your broken v2.10.5 with the new fix version via the F-Droid app.
