### ISSUE TITLE
Start providing APK files for each release

### ISSUE THREAD

**Issue by candroid-man** [ivpn/android-app#307]
# Feature request

Some users like myself have been using Obtainium to get their apps from the source. It's clearly the best way, as of right now I'm not able to use the Android app for IVPN even though the newest release is out, since F-Droid hasn't updated yet.

A new APK should be provided every time the app has a new release here in GitHub so people can get urgent updates like 2.10.6.

**Comment by jurajhilje** [comment]
Since 2.10.6 only fixes the crash on the F-Droid version, the 2.10.5 .apk (https://github.com/ivpn/android-app/blob/develop/CHANGELOG.md#version-2105---2023-12-13) contains all the relevant updates from the new release. I see no point releasing a new 2.10.6 GitHub/website .apk which would be identical to 2.10.5

**Comment by candroid-man** [comment]
If there isn't a new APK, how do I update from 2.10.5 to 2.10.6? F-Droid and every other platform hasn't updated to 2.10.6 either, so I still can't use the app as it won't open

**Comment by jurajhilje** [comment]
I see, as a temporary workaround, you can try following:
- Uninstall the IVPN app and then install 2.10.4 from F-Droid
- Uninstall the IVPN app and then install 2.10.5 from GitHub

**Comment by jurajhilje** [comment]
@candroid-man New version v2.10.6 is now available on F-Droid.

**Comment by candroid-man** [comment]
As I've explained, this issue isn't about this particular version. This issue is about puting APKs in every release so Obtainium users can get IVPN apps directly from the source in an automated way. I'd like to know if the developers would be willing to do this

**Comment by jurajhilje** [comment]
@candroid-man Yes, we will make it so.
