### ISSUE TITLE
Add support for Device Management

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#309]
## Description

There are few updates needed to support the Device Management feature:
* Display assigned device name in the Account screen after login
* Show ‘Visit Device Management’ or ‘Enable Device Management’ action when presenting force log out prompt

**Comment by jurajhilje** [comment]
@gorkapernas IVPNv2.10.7site-Beta-staging.apk is available

**Comment by jurajhilje** [comment]
@gorkapernas I'll update the prompt header text in the next build. Regarding "Cancel" and "Cancel login" - the latter was pulled from the requirements. For me both options are OK, let's just make sure to have the same in all clients.

**Comment by jurajhilje** [comment]
@gorkapernas New APK is available:

- Refactored validation for legacy accounts

**Comment by gorkapernas** [comment]
Verified on IVPNv2.10.7site-Beta-staging.apk, Redmi Note 10 Android 13, Huawei MediaPad Android 8, all the issues reported have been fixed.
Tested with legacy and new account IDs. This is good to go.
