### ISSUE TITLE
IPv6 connection information

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#31]
## Description

IVPN apps load connection information from IVPN API server (`https://api.ivpn.net/v4/geo-lookup`), in several cases:
- After app is launched
- After VPN is connected
- After VPN is disconnected

Current apps only load IPv4 information.

New version of apps will call `/geo-lookup` API with both IPv4 and IPv6 IP addresses by default.

### Control panel IPv4/IPv6 tabs

When both IPv4 and IPv6 connection info is available, results needs to be visible in the Control panel.
A toggle is used to show IPv4 or IPv6 connection information.

### Map IPv4/IPv6 tabs

When both IPv4 and IPv6 connection info is available, but location (city or country) is different, apps need to show "IPv4/IPv6" tabs on the map view with label "Location does not match".

### API access with IP addresses

Our app are using a range of IPv4 addresses used as a fallback if API server cannot be reached with api.ivpn.net hostname.

When app is loading both IPv4 and IPv6 connection information from IVPN API server, app should use provided IPv4 and IPv6 IP address ranges, and not using hostname.

**Comment by gorkapernas** [comment]
Verified on version 2.5.0, staging and production.
Devices -> Samsung Galaxy S10 Android 11 and Huawei MediaPad T5 Android 8.
Tested the following scenarios with all servers which support IPv6 and the disconnected IPv6 info with a private VPN (staging):
- After app is launched
- After VPN is connected
- After VPN is disconnected
- When tapping in the "i" icon from the server popup
- When pausing/resuming the connection
Current behaviour -> When connecting to the VPN with IPv6 enabled for WireGuard, the app shows a switcher with both IPv4 and IPv6 connection info (IP, location and IS), the information can be found in the control panel from the main menu.
Furthermore, if the device network supports IPv6, the app also displays both IPv4 and IPv6 information from the user's real geolocation when the app is not connected to the VPN.
If the IPv4 and IPv6 locations don't match, the app displays a toggle in the map to switch between both locations and the text "Location does not match" is displayed (only when disconnected)

**Comment by AlexKorvin** [comment]
Done
