### ISSUE TITLE
Increase session API calls timeout

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#312]
### Description:
Frequently, when attempting to login, the app does not get a success response in time and kills the create session http request with an "timeout" error. However, the session (device) is created in backend, even though the user is not logged in to the device. 
Apparently, all session API calls are set for 10 seconds timeout.

### Expected result:
It is suggested to increase the timeout for all session API calls. 

**Logs:**
```
6:05:32.797 LoginViewModel : On create session throwable = java.net.SocketTimeoutException: timeout
16:05:32.798 LoginViewModel : Login process: ERROR
```

**Comment by jurajhilje** [comment]
@gorkapernas Available for QA in the latest IVPNv2.10.7site-Beta-staging.apk

**Comment by gorkapernas** [comment]
Verified fixed on latest IVPNv2.10.7site-Beta-staging.apk, the timeout error no longer occurs in short periods, so even if it takes longer to login, the login is always successful and the session is created correctly.
The issue described in the ticket has been fixed.
