### ISSUE TITLE
Include APK in the release assets

### ISSUE THREAD

**Issue by mjdNjhNJ** [ivpn/android-app#314]
# Include APK in the release assets

## Description

Currently there is only an archive with sources in assets when releasing a new version of the app. It is not possible to use IVPN with applications maitaning the versions by hosted APKs like [Obtainium](https://github.com/ImranR98/Obtainium).

## Describe the solution you'd like

It would be nice when APK would be included in assets of each new version like different apps do.

**Comment by candroid-man** [comment]
I requested this in #307.

I saw there was an update 2 days ago and that there was a link to an APK, however for Obtainium to work the APK must be uploaded directly to the GitHub release assets.

**Comment by jurajhilje** [comment]
Hi!
Understood, we will look into it.

**Comment by jurajhilje** [comment]
https://github.com/ivpn/android-app/releases/tag/v2.10.7
APK added in the release assets. We will continue to do so with future releases as well.

**Comment by mjdNjhNJ** [comment]
Works as intended. Thanks for your approach.

**Comment by anthony-robin** [comment]
Hi @jurajhilje, 
Last release (`v2.10.8`) does not seem to contain the `.apk` source and `obtainium`/`zap.store` cannot detect an upgrade exists :(
Would you be able to add back the apk source to the release so that updates can be made with stores that fetch raw source directly ?
Thank you :)

**Comment by jurajhilje** [comment]
@anthony-robin 
https://github.com/ivpn/android-app/releases/tag/v2.10.8
Uploaded the APK binary to the latest release.
Thanks for the reminder!
