### ISSUE TITLE
[F-Droid] Remove Sentry references

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#319]
## Description

Even when app is not using Sentry for crash reports, F-Droid can mark Sentry library references in code as a tracker. So we want to remove all references of Sentry library from the `fdroid/` code.

## QA notes

- Basic sanity check
- Test if app crashes on few different Android devices

**Comment by jurajhilje** [comment]
@gorkapernas Available for QA

**Comment by gorkapernas** [comment]
Verified the latest fdroid apk, tested on different devices running Android 8, 12 and 13, no issues found.
