### ISSUE TITLE
Black screen when interacting with Android app on ChromeOS

### ISSUE THREAD

**Issue by jordan-ivpn** [ivpn/android-app#32]
# Bug report

## Describe your environment

* Device: ChromeBox
* OS name and version: ChromeOS release version: 13729.72.0, Chrome version: 89.0.4389.116, ChromeOS Arc Android SDK version: 28
* IVPN app version: 2.3.1 Google Play Store release
  
## Describe the problem

There is one report of an issue with the IVPN App for Android on ChromeOS where the app's screen goes black when there is any interaction with the app.  It is possible to install the app and log in, but connecting or adjusting any settings results in a black screen.  The map and actual location are displayed, but toggling the connect switch causes the screen to go black.  It is possible to open the app's Settings screen, but any interaction causes the black screen.  Changing the app's theme results in a black screen.

### Steps to reproduce:

[I do not have a ChromeOS device to use to try to replicate the issue.]
  
### Observed Results:

* Any tapping-based interaction with the IVPN App causes a black screen.
![IVPN3](https://user-images.githubusercontent.com/74565577/113370256-a1ef8e80-9320-11eb-8d1d-a772496a96d7.png)
  
### Expected Results:

* There would be no black screen and the IVPN App would connect and be configurable as expected.

### Relevant Code:
n/a

**Comment by AlexKorvin** [comment]
@jordan-ivpn Thank you. Currently we don't support Chrome OS and I don't plan to work on it in the nearest future.
