### ISSUE TITLE
DNS over HTTPS support

### ISSUE THREAD

**Issue by mjdNjhNJ** [ivpn/android-app#322]
# DNS over HTTPS support

## Description

There is no possibility to use DNS with HTTPS encryption on the mobile version of the application while desktop allows it.

## Describe the solution you'd like

Have the same options as on desktop application.

## Describe alternatives you've considered

Currenctly using custom DNS server specified by IPv4 address.

**Comment by mjdNjhNJ** [comment]
Right. I have tagged the OP and awaiting the response.

**Comment by mjdNjhNJ** [comment]
I'm able to set custom secure DNS on Vanadium (Chromium based browser). Couldn't be the same approach used for IVPN as well?

**Comment by jurajhilje** [comment]
> Doesn't the iOS app have a custom implementation of DoH?

Yes it does, because Apple added support for DoH and DoT in their APIs for configuring VPN tunnel in iOS 14.

**Comment by jurajhilje** [comment]
> I'm able to set custom secure DNS on Vanadium (Chromium based browser). Couldn't be the same approach used for IVPN as well?

I don't see how. You can check the docs to see what APIs are available for configuration:
https://developer.android.com/reference/android/net/VpnService.Builder

**Comment by mjdNjhNJ** [comment]
> > I'm able to set custom secure DNS on Vanadium (Chromium based browser). Couldn't be the same approach used for IVPN as well?
> 
> I don't see how. You can check the docs to see what APIs are available for configuration: https://developer.android.com/reference/android/net/VpnService.Builder

I see. Looks like Vanadium use APIs for web browsers which is not possible to use for a VPN app. Just another confirmation that Google privacy & security talks are just [brainwashing campaigs](https://proton.me/blog/google-lobbying). How come that crucial thing is not available in the biggest smartphone operating system in the world. Closing this issue now, hoping to reopen in the future when they add this option.

Anyway, at least,  I'm glad that DNS fallback address is on the roadmap: https://github.com/ivpn/android-app/issues/323
