### ISSUE TITLE
Connection Switcher ignores touches in some cases.

### ISSUE THREAD

**Issue by AlexKorvin** [ivpn/android-app#33]
# Bug report

## Describe your environment

* Device: Pixel 3 
* OS name and version: Android 10 
* IVPN app version: 2.4.0-beta 
  
### Steps to reproduce:

1. Establish a VPN connection using switcher on the main screen.
2. Hide the app and disconnect a VPN using notification.
3. Open the app again and try to establish a VPN connection using switcher on the main screen.
  
### Observed Results:

* Switcher ingores touches.
  
### Expected Results:

* IVPN Client starts to establish VPN connection.

**Comment by gorkapernas** [comment]
Verified fixed on 2.4.0_beta7, Samsung G S10/Android 11, Huawei MediaPad T5/Android 8, the connection toggle is always responsive as expected.
