### ISSUE TITLE
Remove support for Android 7.0 and older

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#335]
Remove support for Android 7.0 and older.

Related to:  
- https://github.com/ivpn/android-app/issues/327

## QA Notes

- General sanity check
- Test OpenVPN with different configuration (ports, AntiTracker, etc.) and different gateways

**Comment by jurajhilje** [comment]
@gorkapernas This is available for QA.

**Comment by gorkapernas** [comment]
Performed a sanity in the latest apks, on Android 12 and 13, everything seems to be working as expected.
