### ISSUE TITLE
F-Droid missing icon

### ISSUE THREAD

**Issue by leoheitmannruiz** [ivpn/android-app#339]
Hey,

just wanted to let you know that F-Droid currently doesn't display an icon at https://f-droid.org/packages/net.ivpn.client/ and in their client. If you want them to do so, you'll have to add an icon.png to https://github.com/ivpn/android-app/tree/develop/fastlane/metadata/android/en-US/images, as per https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure.

**Comment by jurajhilje** [comment]
@leoheitmannruiz Thanks for the report! We will add it in the next app release.
