### ISSUE TITLE
iVPN can't connect and can't add itself to Android VPN list

### ISSUE THREAD

**Issue by jordan-bravo** [ivpn/android-app#340]
# Bug report

## Describe your environment

* Device: Pixel 6  
* OS name and version: GrapheneOS 2024062000  
* IVPN app version: 2.10.8  
  
## Describe the problem

After installing the app and signing in, pressing the toggle button to connect has no effect.  Checking in the OS VPN settings, iVPN is not present.

### Steps to reproduce:

1. Install iVPN.
2. Open app and sign in.
3. Press the toggle button to connect.
  
### Observed Results:

The toggle is not activated and the VPN does not connect.  When I navigate to the OS settings for VPN, there is no entry for iVPN.
  
### Expected Results:

The toggle button should be activated and the VPN should connect.

**Comment by I-I-IT** [comment]
Did you give the app network permission?

**Comment by jordan-bravo** [comment]
I was having a DNS issue with my router and I think that was causing a problem with iVPN.

After resolving the DNS issue, iVPN seems to be working properly.  I am closing this issue.
