### ISSUE TITLE
Update app target to API level 34

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#341]
Resources:
https://support.google.com/googleplay/android-developer/answer/11926878

## QA Notes:

- General sanity check
- Home screen map - test user interaction (move and center map)
- WireGuard protocol (new `android.permission.FOREGROUND_SERVICE_SPECIAL_USE` required for API 34+)
- OpenVPN protocol (new `android.permission.FOREGROUND_SERVICE_SPECIAL_USE` required for API 34+)
- Play Store payments (billing library is updated)
- Test multiple Android versions

**Comment by gorkapernas** [comment]
Verified on 2.10.9, tested all different builds on different devices and Android versions.
All QA points have been tested without encountering any issues. 
This should be good to go.
