### ISSUE TITLE
Add a short description for the IVPN app in the Accrescent listing

### ISSUE THREAD

**Issue by matchboxbananasynergy** [ivpn/android-app#346]
# Feature request

Accrescent has allowed short descriptions for apps for a while, with long descriptions and other metadata to be added eventually. Given that Accrescent has been mirrored in the GrapheneOS app store recently, and more people are coming across IVPN through it, it might be good to provide a short description for the app when you get the chance.

**Comment by jurajhilje** [comment]
@matchboxbananasynergy 
The short description is now added. Thanks for the feedback!
