### ISSUE TITLE
Impossible to enable the VPN from the shortcut/quickAccess bar

### ISSUE THREAD

**Issue by azerios** [ivpn/android-app#352]
# Bug report

## Describe your environment

* Device: Samsung S24+
* OS name and version: Android 14 and OneUi 6.1
* IVPN app version: 2.10.9
  
### Steps to reproduce:

1. Install the 2.10.8 version
2. Enable the VPN by clicking to the shortcut
3. The VPN connection is correctly established
4. Udpate to 2.10.9
  
### Observed Results:

After the update, the click on the shortcut is not creating the connection and I need to open the app to enable it manually.
  
### Expected Results:

After the 2.10.9 update I except that the shortcut will enable and disable the connection successfully
  
Please fix the shortcut behavior.

Regards

**Comment by gorkapernas** [comment]
Verified fixed on version 2.10.10, the IVPN quick action to connect and disconnect from the VPN works as expected.
