### ISSUE TITLE
Tapjacking protection

### ISSUE THREAD

**Issue by ivpn786** [ivpn/android-app#37]
# Feature request

## Description

I don't think I need any descriction for this issue.  Tapjacking protection is absolute need of any app which can have any possibility of finance related activity.

**Comment by AlexKorvin** [comment]
Hey, thank you for message.
I agree that tapjacking protection is absolute need of any app and IVPN has it. 

In the Android it's implemented using secure flag filterTouchesWhenObscured.

https://github.com/ivpn/android-app/blob/master/app/src/main/res/layout/activity_main.xml
