### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by karimi12** [ivpn/android-app#4]
# i get this error in compile time
executing external native build for cmake C:\android-app\app\CMakeLists.txt
Affected Modules: Project-android-app-app

## i use android studio 4 and windows 10

this is my cmake file:
```
cmake_minimum_required (VERSION 3.4.1)
project(IVPN)

add_subdirectory(tools)
add_subdirectory(src/main/cpp)
```

i think ```tools```  directory is problem i can not  find it

**Comment by wiredmartian** [comment]
Were you able to resolve this issue? I'm getting similar error on build 😢

**Comment by AlexKorvin** [comment]
@wiredmartian @karimi12 Hey Guys, please try
`git submodule init`
`git submodule update`
If it doesn't help, please let me know

**Comment by wiredmartian** [comment]
> @wiredmartian @karimi12 Hey Guys, please try
> `git submodule init`
> `git submodule update`
> If it doesn't help, please let me know

Awesome! Yeah this worked
