### ISSUE TITLE
KillSwitch Not working if Always-on VPN is not set to ON in Android settings.

### ISSUE THREAD

**Issue by ivpn786** [ivpn/android-app#42]
# Bug report

## Describe your environment

* Device: 
* OS name and version: Android 10
* IVPN app version: 2.4.0 site apk 
  
## Describe the problem
KillSwitch toggle goes off whenever we quit settings. This seems to occur when app is not set as always-on-VPN in android settings but I haven't looked into that much.
### Steps to reproduce:

1. Launch app and go to kill switch settings. Turn it ON.
2. Press back and again go into KillSwitch settings.
3. Find that turned off.
  
### Observed Results:

KillSwitch toggle goes off. And also killswitch isn't working.
  
### Expected Results:
It should remain turn on.

**Comment by AlexKorvin** [comment]
@ivpn786 Thank you for the report. Unfortunately, I can't reproduce it. Kill-switch works as expected for me. Could you please provide additional information? For example, do you use network protection? If yes, did you enable "Enable Kill-switch" or "Disable Kill-switch" rules?

Also, can I ask you screen recording of your steps?

**Comment by ivpn786** [comment]
I am not able to reproduce it recently. But I've definitely reproduced it multiple times on 2.4.0
My settings are-

1. No Network Protection ( obviously I've asked for #35 )
2. Multi-hop
3. No Split-tunnel
4. OpenVPN 443
5. No Bypass local network
6. No Always-ON in Android settings

Then tried to turn on Killswitch toggle of IVPN application and press back. Again look on same setting by going into kill switch settings. And find kill switch toggle off.
It only occured when Android Always-on setting was off.
I'll provide screenrecords if I can reproduce.

**Comment by ivpn786** [comment]
Not able to reproduce now. I don't know what's going on. @lsm5, you have Android 10. Can you try to reproduce?

**Comment by ivpn786** [comment]
Ok, this issue was not because of IVPN. It was due to Interference by another VPN. So closing, Sorry.
