### ISSUE TITLE
2.4.0 crashes on android 10 with mock location setup enabled + server change

### ISSUE THREAD

**Issue by lsm5** [ivpn/android-app#43]
# Bug report

## Describe your environment

* Device: Samsung Galaxy Note 9  
* OS name and version: Android 10
* IVPN app version: 2.4.0 [Downloaded from ivpn.net]
  
### Steps to reproduce:

1. Setup Mock location provider to IVPN
2. Choose any server on IVPN and connect to VPN [Works fine once]
3. Change to any other server

### Observed Results:

Once the app crashes, the crash keeps occurring on relaunching the app, even after undoing the mock location app change. The app crash persists across reboots as well. I had to uninstall and reinstall the app to get it working again.

### Expected Results:

No crash when I change server repeatedly with mock location enabled.

**Comment by AlexKorvin** [comment]
@lsm5 Thank you for report. I'm going to release fix for this issue ASAP.

**Comment by AlexKorvin** [comment]
It's an Android 10 specific issue.

**Comment by gorkapernas** [comment]
Verified on v4.2.1, as @AlexKorvin commented, the crash only happens on Android 10 devices which handle the Mock Location feature differently, on this new version of IVPN, the issue should be solved. 
Also note that on lower or higher Android versions, the Mock Location feature should already work as expected.

@lsm5 please let us know if the issue is solved on your side once we release the new version.

**Comment by lsm5** [comment]
> @lsm5 please let us know if the issue is solved on your side once we release the new version.

@gorkapernas sure thing, any ETA on 2.4.1 release on the website?

**Comment by lsm5** [comment]
v2.4.1 looks great. Changed the server more than 5 times, works flawlessly. Thanks for the fix!

Closing...

**Comment by lsm5** [comment]
So, while server change didn't seem to cause any issues, the app seems to crash after a reboot if mock location setting is disabled and phone is later rebooted.

1. Set mock location to IVPN and connect IVPN
2. Change VPN server any number of times (works fine)
3. Disable mock location
4. Reboot phone
5. IVPN constantly crashes

Also, it looks like either IVPN itself or maybe the mock location setup in particular consumes a lot more battery than 2.4.0

**Comment by lsm5** [comment]
>     1. Set mock location to IVPN and connect IVPN
> 
>     2. Change VPN server any number of times (works fine)
> 
>     3. Disable mock location
> 
>     4. Reboot phone
> 
>     5. IVPN constantly crashes
> 

Now if I re-enable mock location setup to IVPN and then connect, it works just fine once again :D 

So, it seems once you set mock location, the app expects it to enabled all the time. 

Hope that helps.

**Comment by gorkapernas** [comment]
@lsm5 Thanks for the report, it's appreciated.

We'll take a closer look, but it looks like another Android 10 related issue. We'll get back to you once we are able to reproduce and fix it.

**Comment by ivpn786** [comment]
Not able to reproduce on Android 10 with 2.4.1 and above mentioned steps. It's working flawless for me.

**Comment by lsm5** [comment]
> @lsm5 Thanks for the report, it's appreciated.
> 
> We'll take a closer look, but it looks like another Android 10 related issue. We'll get back to you once we are able to reproduce and fix it.

@gorkapernas no rush. I don't expect to change that setting and reboot frequently, so it's not a big deal. I guess the priority can be lowered too.

Thanks for all the good work!

**Comment by lsm5** [comment]
hmm, I can't see the issue anymore like @ivpn786 mentioned. So, I'll just blame it on my phone. Re-closing this :D .. I'll get back if I have a consistent reproducer.
