### ISSUE TITLE
Network Protection notification does not disappear

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#48]
### Description:
On Android 11 OS, when Network Protection and KillSwitch are enabled, if the user logs out, the notification about Network Protection does not disappear. When logging back in, the notification will remain visible, even though Network Protection is disabled.
At this point, the only way to make the notification to disappear is to enable Network Protection and disable it again.

**Note:**
So far only reproduced on my Android 11 device - Samsung Galaxy S10

### Actual result:
Network Protection notification does not disappear after logging out.

### Expected result:
Network Protection notification should disappear after logging out since the feature is disabled automatically.

### Steps to reproduce:
1. Install version 2.4.1 on an Android 11 device.
2. Login.
3. Enable Network Protection.
4. Observe that the notification appears.
5. Enable KillSwitch.
6. Logout.
7. Observe that the notification about Network Protection does not disappear.

### Environment:
Device: Samsung G S10/Android 11 
IVPN version: 2.4.1

**Comment by gorkapernas** [comment]
Verified fixed on version 2.4.0_beta3, Samsung Galaxy S10/Android 11, Xiaomi Redmi 5/Android 8.1,  Huawei MediPad T5/Android 8.

The notification disappears after logging out, the issue no longer occurs, although the issue only happened on Android 11 devices, I confirm the expected behaviour in other Android versions/devices.

**Comment by AlexKorvin** [comment]
Done
