### ISSUE TITLE
App randomly disconnecting from VPN 

### ISSUE THREAD

**Issue by pilsnerbeer** [ivpn/android-app#5]
# Bug report

## Describe your environment

* Device: OP5T
* OS name and version: 10 
* IVPN app version: 1.68
  
## Describe the problem
The app will randomly disconnect from VPN. Last time this happened I was actively using my phone, the device vibrated twice and I noticed a notification from always-on agent:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/87026997-d04e9c00-c1dc-11ea-93b1-575f8669392c.png)

Notice the notification above - IVPN is supposedly "still connected". This is not correct and can be verified by looking up one's IP address. At this time, the device was not connected to VPN anymore.

### Steps to reproduce:

1. connect to IVPN & make sure always-on VPN is enabled
2. ??? let time pass
3. observe the always-on notification appearing signalizing you're no longer connected. Alternatively, check your public IP from time to time.
  
### Observed Results:

Additional screenshot shows my battery optimization setting:

![Screenshot_2](https://user-images.githubusercontent.com/36133540/87027311-4b17b700-c1dd-11ea-8255-91df58cc8134.png)

  
### Expected Results:

* What did you expect to happen?  
VPN should stay ON at all times. If not, the notification of connection must disappear.

**Comment by ivpn786** [comment]
Is this still an issue @pilsnerbeer ?

**Comment by pilsnerbeer** [comment]
@ivpn786 sorry but I no longer have IVPN subscription. good luck
