### ISSUE TITLE
App connects without WG key when connecting to an untrusted network

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#51]
### Description:
Currently If the current network is set to untrusted and the app fails to regenerate a WG key because of e.g. no internet connection (airplane mode for testing), once you reestablish the connection, the app will not generate a new key upon connecting automatically (because trust status), so the app will be connected to the VPN without a key, consequently there will be no internet traffic on the device.

### Actual result:
When WG rotation fails, the app will connect without WG key when connecting to an untrusted network

### Expected result:
The app should present an error and remain disconnected, so the user can connect manually and regenerate the new key.

### Steps to reproduce:
1. Install 2.4.1.
2. Login.
3. Enable Network Protection + set current network to untrusted.
4. Enable Airplane mode.
5. Disconnect from the VPN.
6. Attempt to regenerate manually a new key - it fails, so the app removes the old key.
7. Disable Airplane mode.
8. Observe that the app connects to the VPN (due to untrusted status), but there is no internet traffic.
9. When going to the WG details screen, it is observed that the new key is not generated.

### Environment:
IVPN: 2.4.1
Devices: Samsung Galaxy S10, Android 11

**Comment by gorkapernas** [comment]
Verified fixed on version 2.4.0_beta3, Samsung Galaxy S10/Android 11, Xiaomi Redmi 5/Android 8.1,  Huawei MediPad T5/Android 8.
Now the app also generates a new key when connecting automatically (due to untrusted status) after reestablishing the internet connection, if the regeneration fails, the app presents an error as follows.
![wg key error](https://user-images.githubusercontent.com/16647612/115570069-1da87f80-a2be-11eb-847b-ef1cd0ef2d93.png)

**Comment by AlexKorvin** [comment]
Done
