### ISSUE TITLE
Default trust status is always reverted to None

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#53]
### Description:
On version 2.4.1, when setting the default trust status to Untrusted/Trusted, the trust status is always reverted back to None. The issue does not happen the first time the trust status is changed, but when logging out and logging back in, from this moment on, it is not possible to change the default to Untrusted or Trusted.

**Note:**
The issue happens in all devices, Android OS.
This issue might be related to the changes implemented on https://github.com/ivpn/android-app/issues/48

### Actual result:
Default trust status is always reverted to None.

### Expected result:
User should always be able to change the trust status of default, mobile and current network.

### Steps to reproduce:
1. Install 2.4.1.
2. Login.
3. Enable Network Protection.
4. Set default to untrusted - app connects automatically.
5. Disconnect from VPN.
6. Enable KillSwitch.
7. Logout.
8. Log back in.
9. Set default to Untrusted - nothing happens.
10. Access network protection again, default is reverted to none.

### Environment:
IVPN: 2.4.1
Devices: Samsung Galaxy S10/Android 11, Xiaomi Redmi 5/Android 8.1

**Comment by gorkapernas** [comment]
Verified fixed on version 2.4.0_beta3, Samsung Galaxy S10/Android 11, Xiaomi Redmi 5/Android 8.1,  Huawei MediPad T5/Android 8.

The trust status is not reset to None anymore, Network Protection works as expected.

**Comment by AlexKorvin** [comment]
Done
