### ISSUE TITLE
Use same fastest server configuration for OpenVPN and WireGuard

### ISSUE THREAD

**Issue by gorkapernas** [ivpn/android-app#59]
### Description:
Currently, each protocol can have a different fastest server configuration to be used as the fastest servers.

The fastest server configuration should be the same for all protocols, so even if the server lists differs, if user deselect one location, it should be saved for all protocols.

**Note:**
Already implemented on iOS.

**Comment by gorkapernas** [comment]
@jurajhilje there is one issue when updating the apk to the newest version, after the update, the fastest configuration set in the old version, if different for each protocol, will still be different in the new version.

**Steps:** 
- Old app v2.8.5 - e.g  deselect Amsterdam and Lisbon for OpenVPN, deselect Atlanta and Franca for WireGuard.
- Update the apk from 2.8.5 to 2.8.6.
- Launch the app.
- Observe that the fastest server configuration is still different for each protocol.

**Expected:**
The app should have the same fastest server configuration on both protocols
i.e. taking the example from the steps above, Amsterdam, Lisbon, Atlanta and Franca should be deselected for both OpenVPN and WireGuard.

Note:
I used the site version to test the update, with the store version, the app fails to update.

**Comment by jurajhilje** [comment]
@gorkapernas 
This is actually expected in the updated code/logic. It is not intendet to "merge" both settings after APK upgrade, but rather have the same settings when using the new app version.
So I would like to keep this as it is for few reasons:
- I do not want to introduce the extra code in the app that will serve as migration logic from the old to the new app version.
- Some users might expect to keep existing settings until they manually update them, so the app settings are not changed just by APK upgrade.

Also related to https://github.com/ivpn/android-app/issues/120 and https://github.com/ivpn/android-app/issues/199

**Comment by gorkapernas** [comment]
@jurajhilje understood, I'll move the ticket to deployable as no other issues have been found.
