### ISSUE TITLE
TransactionTooLargeException

### ISSUE THREAD

**Issue by borden-a1** [ivpn/android-app#64]
We used a static analysis tool to analyze ivpn and found that ivpn will invoke `getInstalledApplications` in `SplitTunnelingViewModel.InflateApplicationInfoAsyncTask`.

This function will use binder to get all apps' infos in this device, which will cause `TransactionTooLargeException` and crash ivpn with many apps installs.
Some similar issues could be found in [AdAway](https://github.com/AdAway/AdAway/issues/617), [ShoppingList](https://github.com/openintents/shoppinglist/issues/26).
We suggest that the invocation should be surrounded by try/catch, or add more arguments to limit return data size.

```
InflateApplicationInfoAsyncTask(PackageManager packageManager) {
    this.packageManager = packageManager;
    this.applicationInfoList = packageManager.getInstalledApplications(PackageManager.GET_META_DATA);
}
```

**Comment by gorkapernas** [comment]
Verified on 2.8.4, tested on Huawei Media Tab Android 8, Redmi Note 10 Android 11, Pixel 4 Android 13.
The issue has been fixed, the crash should not occur anymore.
