### ISSUE TITLE
Split Tunneling for system-apps

### ISSUE THREAD

**Issue by jacktheripper19** [ivpn/android-app#67]
# Feature request

## Description

I'm not sure if this is already used but I want to make sure that the split tunnelling is working also for system-apps so that I can mimic the behaviour of network filtering apps like NetGuard. 

The idea is to  enable Kill switch and Always-on VPN both from the app and natively in the system, then using tunnelling enable only apps that I'm willingly giving permission for internet access.

I found the kill switch really useful for this to replace NetGuard as it already uses the only VPN slot in Android, but at least it allows managing the rules for system apps while in IVPN I see only user apps in the list, so I'm not quite sure if this is working well.

## Describe the solution you'd like

If possible, allow managing system apps in split tunnelling or add a feature that block access to internet for certain app.

## Describe alternatives you've considered

Alternatives that I'm aware of are rooting the phone to use apps that filter based on iptables like AFWall+ then use the VPN app. rooting is not a good solution for many people. NetGuard supports using SOCKS for routing but that's not possible with IVPN

Thank you

**Comment by 52730204** [comment]
I tested this with NextDNS and can confirm system apps are not affected by the split tunneling feature.

**Comment by spurls** [comment]
I too would like this feature, but for a different reason.
I want to run the VPN all the time, however Android Auto will not run with a VPN active.
I simply want to exclude Android Auto using the Split Tunneling. I was able to do this with the Mulvad app which provided full functionality of Android Auto while keeping the Always on VPN active.

IVPN is a superior company, so I'd rather stay with you, but I'd like this feature. Otherwise the only workaround would be to mark my mobile network as trusted which Id prefer not to do.

**Comment by jurajhilje** [comment]
@gorkapernas This is available in the new `IVPNv2.10.5site-Beta.apk`. Now there is a new "Show system apps" toggle in the Split Tunneling screen.

**Comment by gorkapernas** [comment]
@jurajhilje I can see some system apps even when the option "Show system apps" is disabled, apps such as "Analytics" or "Android Auto" which are always displayed for me in the Split Tunnelling list of apps, I believe these apps should be hidden and only be displayed when the user enables "Show system apps".

Also there seems to be an issue with the option "TURN ON/OFF ALL", not all applications are disabled when trying to turn them off all, in my case, the app "Downloads" remains enabled.

Tested on Android 13 ^^

**Comment by jurajhilje** [comment]
@gorkapernas New beta APK is available. Let me know how it goes.

**Comment by gorkapernas** [comment]
Verified in the new beta apk, tested on different devices, the issues mentioned in my previous comment have been fixed.
System apps are only displayed in the Split Tunnel list when the option "Show system apps" is enabled.
Also the issue with certain apps remaining enabled after turning all off has been resolved.
This is good to go.
