### ISSUE TITLE
v2.4.1 `CHECK FOR UPDATES` didn't work

### ISSUE THREAD

**Issue by lsm5** [ivpn/android-app#68]
# Bug report

## Describe your environment

* Device: Samsung Note 9
* OS name and version: Android 10  
* IVPN app version: 2.4.1
  
### Steps to reproduce:

1. On 2.4.1, hit `CHECK FOR UPDATES` in `Settings -> Updates`

  
### Observed Results:

Says `You are using the latest version`

### Expected Results:

Should've shown me 2.5.1 available.

**Comment by lsm5** [comment]
This happened around 2030 EDT on 2021-06-30.  I manually installed 2.5.1 from the site.

**Comment by AlexKorvin** [comment]
It's fixed. I've tested on the new 2.6.0 version
