### ISSUE TITLE
F-Droid can't build due to com.android.billingclient

### ISSUE THREAD

**Issue by linsui** [ivpn/android-app#72]
com.android.billingclient is not foss so it's not allowed in F-Droid. I'll disable affected versions. Could you please remove com.android.billingclient from fdroid flavor? Thanks!

**Comment by AlexKorvin** [comment]
@linsui Hello, I'm not sure I can remove library only for specific build flavor. I'm going to investigate this question.

 If not, As an alternative solution I'm going to split project to the submodules. But I need time for this.

**Comment by linsui** [comment]
Thanks!

**Comment by AlexKorvin** [comment]
@linsui 
Morning. I implemented necessary changes into the project. The new submodule fdroid doesn't contain a billing library for Android. 
Here is the Gradle command I'm using to build the release version:

./gradlew :fdroid:assembleProductionRelease

FYI, The latest release v2.6.0 contains all these changes.

Is anything else from our side that should be done to return the IVPN client to F-Droid?

**Comment by linsui** [comment]
Thanks! But somehow `com.google.android.play.core` is pulled in. I don;t know where it comes from. Could you please take a look? The log is https://gitlab.com/linsui/fdroiddata/-/jobs/1450255296.

**Comment by AlexKorvin** [comment]
@linsui I figured it out. It comes from 
`androidx.navigation:navigation-dynamic-features-fragment` library.
I removed it from the F-Droid submodule. Also, I updated the v2.6.0 tag. I hope the project will be built successfully now.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9444 Thanks!
