### ISSUE TITLE
DNS leaks and Antitracker not working.

### ISSUE THREAD

**Issue by ivpn786** [ivpn/android-app#74]
# Bug report

## Describe your environment

* Device: _____  Xiomi device
* OS name and version: _____  Android 10
* IVPN app version: _____  2.6.0 site
  
## Describe the problem
IVPN 2.6.0 site version works excellent with no leaks whatsoever with openvpn. Antitracker also work flawless. But while connected with wireguard DNS leaks occurs. It uses Google DNS servers not IVPN one in that situation. Although Antitracker is ON in Hardcore mode, I can run all Google services.
### Steps to reproduce:

1. _____Set Wireguard as Protocol.
2. _____Set Antitracker in Hardcore mode.
3. _____Connect and check any website for used DNS servers and try to use Google services.
4. _____Observe undesired behaviour.
  
### Observed Results:

* What happened? This could be a description, log output, etc.  
  DNS from Google are being used and Antitracker not working.
### Expected Results:

* What did you expect to happen?  
  DNS from IVPN should be used and Antitracker works like charm as happens with OpenVPN.
### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by ivpn786** [comment]
I don't know the reason but issue seems to resolved for me.
Can anyone with Android 10 device confirm this issue? maybe @lsm5

**Comment by lsm5** [comment]
@ivpn786 antitracker enabled and https://dnsleaktest.com doesn't show any unwanted DNS servers. Perhaps you earlier had  private dns setup in your connection settings?

**Comment by ivpn786** [comment]
Have you tested with Wireguard @lsm5? Funny thing is It was 100% reproducible and I wasn't using Private DNS. But I tested it on ipleak.net both times.
Anyways it's not an issue for me now.

**Comment by lsm5** [comment]
> Have you tested with Wireguard @lsm5? Funny thing is It was 100% reproducible and I wasn't using Private DNS. But I tested it on ipleak.net both times.
> Anyways it's not an issue for me now.

Yes, i use wireguard by default. I earlier didn't have hardcore mode, but just now tested with hardcore mode and both dnsleaktest and ipleak report only 1 (expected) dns server, no google dns.
