### ISSUE TITLE
Add an Indian server 

### ISSUE THREAD

**Issue by deep0808** [ivpn/android-app#89]
I was going to subscribe to IVPN but than I found out there no Indian server so at moment i choosed to opt out. But if you add the request server I'll be a lifetime subscriber I promise. Also there no Taiwan or Chinese server either it kind turn off for a such a great vpn. That it I hope you pay attention.

**Comment by AlexKorvin** [comment]
@deep0808 Thank you for ticket. I passed information to my colleagues. We will pay attention on it.
