### ISSUE TITLE
error=2, No such file or directory

### ISSUE THREAD

**Issue by AamirRiaz** [ivpn/android-app#90]
I got this error when i try to run the project. Please guide me whats the problem. I just want to take the clone for testing purpose. Thanks in advance

**Comment by AlexKorvin** [comment]
@AamirRiaz Could you please provide more information about this error? Do you build using console or Android Studio? Also, please share some logs.

**Comment by AlexKorvin** [comment]
@AamirRiaz Hey again, could you please pull changes and try to build the project again?

**Comment by AamirRiaz** [comment]
It is giving me a same error after fetching changes. Do i need to install Swig before compiling this project? 
I am posting here some errors which i got on the android studio.

Execution failed for task ':core:generateOpenVPN3Swigdebug'.
> A problem occurred starting process 'command 'swig''

Execution failed for task ':core:generateJsonModelDebug'.
> /Users/zainanjum/StudioProjects/android-app/core/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /Users/zainanjum/Library/Android/sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at
    least version "3.0")
  Call Stack (most recent call first):
    /Users/zainanjum/Library/Android/sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /Users/zainanjum/Library/Android/sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindSWIG.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    src/main/cpp/CMakeLists.txt:38 (FIND_PACKAGE)

**Comment by AamirRiaz** [comment]
@AlexKorvin Hey,

Would you please check for a while? I am still stuck on it.
Thanks In Advance

**Comment by AamirRiaz** [comment]
@AlexKorvin Hey,

Would you please check for a while? I am still stuck on it.
