### ISSUE TITLE
Keep the app settings on logout

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/android-app#94]
Currently, the IVPN app is erasing application settings when a user logs out.

This has to be changed:

* Keep the app configuration on logout by default
* In the logout prompt, add an additional option to Log out and clear app settings

**Comment by gorkapernas** [comment]
Verified on version 2.8.0, Samsung Galaxy S10 Android 11 and Xiaomi Redmi 5 Android 8.1, now the app resets the protocol to WireGuard when clearing app settings on log out. 
This is good to go.
